routes/web.php
<?php

use App\Http\Controllers\PersonController;
use App\Http\Controllers\WebsiteFrontEnd\WebsiteController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



//Route::get('/', function () {
//   return view('welcome');
//});

Auth::routes(['verify' => true,
    'register' => true,
    'reset' => false,
]);

Route::get('/refereshcaptcha', 'App\Http\Controllers\Auth\LoginController@refereshCaptcha');

//Custom Auth Routes
// Authentication Routes...

// Password Reset Routes...
/*$this->get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm');
$this->post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail');
$this->get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm');
$this->post('password/reset', 'Auth\ResetPasswordController@reset');*/

Route::group(['middleware' => ['auth']], function () {

    Route::mediaLibrary();

    Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

    Route::resource('roles', App\Http\Controllers\RoleController::class);

    Route::resource('permissions', App\Http\Controllers\PermissionController::class);

    Route::resource('users', App\Http\Controllers\UserController::class);

    Route::get('profil', [App\Http\Controllers\UserController::class, 'profil'])->name('profil');
    Route::get('editProfil/{id}', [App\Http\Controllers\UserController::class, 'editProfiles']);
    Route::patch('updateProfile/{id}', [App\Http\Controllers\UserController::class, 'updateProfile']);

    Route::resource('galeris', App\Http\Controllers\GaleriController::class);


    Route::resource('posts', 'App\Http\Controllers\PostController');

    Route::resource('postCategories', 'App\Http\Controllers\PostCategoryController');
    Route::post('postCategoriesIncrease/{id}', 'App\Http\Controllers\PostCategoryController@increase')->name('postCategoriesIncrease');
    Route::post('postCategoriesDecrease/{id}', 'App\Http\Controllers\PostCategoryController@decrease')->name('postCategoriesDecrease');

    Route::resource('pendidikans', 'App\Http\Controllers\PendidikanController');

    Route::resource('profiles', 'App\Http\Controllers\ProfileController');
    Route::get('editProfiles/{id}', [\App\Http\Controllers\ProfileController::class,'editInfo']);

    Route::resource('portofolios', 'App\Http\Controllers\PortofolioController');

    Route::resource('people', 'App\Http\Controllers\PersonController');

    Route::resource('personHasPendidikans', 'App\Http\Controllers\PersonHasPendidikanController');

    Route::resource('skills', 'App\Http\Controllers\SkillController');

    Route::resource('personSkills', 'App\Http\Controllers\PersonSkillController');

    Route::resource('sosmedPeople', 'App\Http\Controllers\SosmedPersonController');

    Route::resource('personPortofolios', 'App\Http\Controllers\PersonPortofolioController');

    Route::resource('jenisPortofolios', 'App\Http\Controllers\JenisPortofolioController');

    Route::get('synchronize-anggota',[PersonController::class,'synchronize'])->name('synchronizeAnggota');
});

//----WEBSITE FRONT END
Route::get('/', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'index'])->name('beranda');
//

//
////Post Category
Route::get('galeri-foto', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'galeriFoto'])->name('galeri-foto');
Route::get('galeri-foto/{slug}', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'detailGaleriFoto'])->name('detail-galeri-foto');

Route::get('/',[WebsiteController::class,'index'])->name('beranda');
////Detail Post
Route::get('post/{slug}', [WebsiteController::class,'detailPost'])->name('detail-post');
Route::get('page/{slug}', [\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'detailPage'])->name('detail-page');

Route::get('person',[\App\Http\Controllers\WebsiteFrontEnd\WebPersonController::class,'person'])->name("persons");
Route::get('person/{slug}',[\App\Http\Controllers\WebsiteFrontEnd\WebPersonController::class,'personDetail'])->name("detail-person");
Route::get('portofolio',[WebsiteController::class,'portofolio'])->name('portofolio');
Route::get('mitra',[\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'mitra'])->name("mitra-britech");

Route::get('instagram',function (){
    $data=Dymantic\InstagramFeed\Profile::feed($limit = 20);
    return $data;

});
Route::get('tentang',[\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'tentang'])->name("tentang");
Route::get('pengurus',[\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'pengurus'])->name("pengurus");
Route::get('detail_pengurus/{slug}',[\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'detailPengurus'])->name("detailPengurus");
Route::get('caradaftar',[\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'caradaftar'])->name("caradaftar");
Route::get('daftar',[\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'daftar'])->name("daftar");
Route::get('anggota',[\App\Http\Controllers\WebsiteFrontEnd\WebsiteController::class,'anggota'])->name("anggota");

app/Models/PersonHasPendidikan.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Factories\HasFactory;

/**
 * Class PersonHasPendidikan
 * @package App\Models
 * @version June 11, 2021, 1:33 am UTC
 *
 * @property \App\Models\Pendidikan $pendidikan
 * @property \App\Models\Person $person
 * @property integer $person_id
 * @property integer $pendidikan_id
 * @property string $perguruan_tinggi
 * @property string $program_studi
 * @property string $tahun_lulus
 * @property string $person_has_pendidikancol
 * @method static create(array $array)
 */
class PersonHasPendidikan extends Model
{
    use SoftDeletes;

    use HasFactory;

    public $table = 'person_has_pendidikan';

    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];



    public $fillable = [
        'person_id',
        'pendidikan_id',
        'tahun_lulus',
        'perguruan_tinggi',
        'program_studi',
        'person_has_pendidikancol'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'person_id' => 'integer',
        'pendidikan_id' => 'integer',
        'perguruan_tinggi' => 'string',
        'program_studi' => 'string',
        'tahun_lulus' => 'string',
        'person_has_pendidikancol' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
//        'person_id' => 'required',
//        'pendidikan_id' => 'required',
//        'perguruan_tinggi' => 'nullable|string|max:255',
//        'program_studi' => 'nullable|string|max:255',
//        'tahun_lulus' => 'nullable|string|max:45',
//        'person_has_pendidikancol' => 'nullable|string|max:45',
//        'created_at' => 'nullable',
//        'updated_at' => 'nullable',
//        'deleted_at' => 'nullable'
    ];

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function pendidikan()
    {
        return $this->belongsTo(\App\Models\Pendidikan::class, 'pendidikan_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function person()
    {
        return $this->belongsTo(\App\Models\Person::class, 'person_id');
    }
}

app/Http/Controllers/PersonHasPendidikanController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreatePersonHasPendidikanRequest;
use App\Http\Requests\UpdatePersonHasPendidikanRequest;
use App\Models\Pendidikan;
use App\Models\PersonHasPendidikan;
use App\Repositories\PersonHasPendidikanRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

class PersonHasPendidikanController extends AppBaseController
{
    /** @var  PersonHasPendidikanRepository */
    private $personHasPendidikanRepository;

    public function __construct(PersonHasPendidikanRepository $personHasPendidikanRepo)
    {
        $this->personHasPendidikanRepository = $personHasPendidikanRepo;
    }

    /**
     * Display a listing of the PersonHasPendidikan.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $personHasPendidikans = $this->personHasPendidikanRepository->all();

        return view('person_has_pendidikans.index')
            ->with('personHasPendidikans', $personHasPendidikans);
    }

    /**
     * Show the form for creating a new PersonHasPendidikan.
     *
     * @return Response
     */
    public function create(Request $request)
    {
        $person_id = $request['person_id'];
        $pendidikan = Pendidikan::pluck('name','id');

        $data = PersonHasPendidikan::where('person_id',$person_id)->get();

        return view('person_has_pendidikans.create',compact('pendidikan','person_id','data'));
    }

    /**
     * Store a newly created PersonHasPendidikan in storage.
     *
     * @param CreatePersonHasPendidikanRequest $request
     *
     * @return Response
     */
    public function store(CreatePersonHasPendidikanRequest $request)
    {
        $input = $request->all();

        $personHasPendidikan = $this->personHasPendidikanRepository->create($input);

        Flash::success('Person Has Pendidikan saved successfully.');

//        return redirect(route('personHasPendidikans.index'));
        return redirect(url()->previous());

    }

    /**
     * Display the specified PersonHasPendidikan.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $personHasPendidikan = $this->personHasPendidikanRepository->find($id);

        if (empty($personHasPendidikan)) {
            Flash::error('Person Has Pendidikan not found');

            return redirect(route('personHasPendidikans.index'));
        }

        return view('person_has_pendidikans.show')->with('personHasPendidikan', $personHasPendidikan);
    }

    /**
     * Show the form for editing the specified PersonHasPendidikan.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id, Request $request)
    {
        $person_id = $request['person_id'];
        $pendidikan = Pendidikan::pluck('name','id');

        $personHasPendidikan = $this->personHasPendidikanRepository->find($id);

        if (empty($personHasPendidikan)) {
            Flash::error('Person Has Pendidikan not found');

            return redirect(route('personHasPendidikans.index'));
        }

        return view('person_has_pendidikans.edit',compact('person_id','pendidikan'))->with('personHasPendidikan', $personHasPendidikan);
    }

    /**
     * Update the specified PersonHasPendidikan in storage.
     *
     * @param int $id
     * @param UpdatePersonHasPendidikanRequest $request
     *
     * @return Response
     */
    public function update($id, UpdatePersonHasPendidikanRequest $request)
    {
        $personHasPendidikan = $this->personHasPendidikanRepository->find($id);

        if (empty($personHasPendidikan)) {
            Flash::error('Person Has Pendidikan not found');

            return redirect(route('personHasPendidikans.index'));
        }

        $personHasPendidikan = $this->personHasPendidikanRepository->update($request->all(), $id);

        Flash::success('Person Has Pendidikan updated successfully.');

//        return redirect(route('personHasPendidikans.index'));
        return redirect(url()->previous());

    }

    /**
     * Remove the specified PersonHasPendidikan from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $personHasPendidikan = $this->personHasPendidikanRepository->find($id);

        if (empty($personHasPendidikan)) {
            Flash::error('Person Has Pendidikan not found');

            return redirect(route('personHasPendidikans.index'));
        }

        $this->personHasPendidikanRepository->delete($id);

        Flash::success('Person Has Pendidikan deleted successfully.');

//        return redirect(route('personHasPendidikans.index'));
        return redirect(url()->previous());
    }
}

resources/views/person_has_pendidikans/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="content-body">
        <section id="horizontal-form-layouts">
            <div class="row">
                <div class="col-md-12">
                    <div class="card overflow-hidden">
                        <div class="card-content">
                            <div class="media align-items-stretch">
                                <div class="bg-green p-2 media-middle">
                                    <i class="fa fa-pencil-square font-large-2 text-white"></i>
                                </div>
                                <div class="media-body p-1">
                                    <span class="green font-medium-5">Input Person Has Pendidikan</span><br>
                                    <span style="margin-top: -5px">Membuat Person Has Pendidikan Baru</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    @include('adminlte-templates::common.errors')
                    <div class="card">
                        <div class="card-content collpase show">
                            <div class="card-body">
                                {!! Form::open(['route' => 'personHasPendidikans.store'], ['class' => 'form']) !!}
                                <div class="form-body">
                                    @include('person_has_pendidikans.fields')
                                </div>
                                {!! Form::close() !!}


                                <table class="table table-striped mt-3">
                                    <thead>
                                    <tr>
                                        <th>No.</th>
                                        <th>Nama Jenjang Pendidikan</th>
                                        <th>Program Studi</th>
                                        <th>Tahun Lulus</th>
                                        <th>Perguruan Tinggi</th>
                                        <th>#</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($data as $index => $item)
                                        <tr>
                                            <td>{{ $index+1 }}</td>
                                            <td>{{ $item['pendidikan']->name }}</td>
                                            <td>{{ $item->program_studi }}</td>
                                            <td>{{ $item->tahun_lulus }}</td>
                                            <td>{{ $item->perguruan_tinggi }}</td>
                                            <td>
                                                {!! Form::open(['route' => ['personHasPendidikans.destroy', $item->id], 'method' => 'delete']) !!}
                                                <div class="btn-group" role="group" aria-label="Basic example">
                                                    <a href="{{ url('personHasPendidikans/'.$item->id.'/edit') }}" class="btn btn-success btn-sm"><i class="fa fa-pencil-square"></i></a>
                                                    {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-sm btn-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                                                </div>
                                                {!! Form::close() !!}
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/person_has_pendidikans/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="content-body">
        <section id="horizontal-form-layouts">
            <div class="row">
                <div class="col-md-12">
                    <div class="card overflow-hidden">
                        <div class="card-content">
                            <div class="media align-items-stretch">
                                <div class="bg-indigo p-2 media-middle">
                                    <i class="fa fa-pencil-square font-large-2 text-white"></i>
                                </div>
                                <div class="media-body p-1">
                                    <span class="indigo font-medium-5">Perubahan Person Has Pendidikan</span><br>
                                    <span style="margin-top: -5px">Melakukan Perubahan Person Has Pendidikan </span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    @include('adminlte-templates::common.errors')
                    <div class="card">
                        <div class="card-content collpase show">
                            <div class="card-body">
                                {!! Form::model($personHasPendidikan, ['route' => ['personHasPendidikans.update', $personHasPendidikan->id], 'method' => 'patch']) !!}
                                <div class="form-body">
                                    @include('person_has_pendidikans.fields')
                                </div>
                                {!! Form::close() !!}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/person_has_pendidikans/fields.blade.php
<input type="text" id="person_id" name="person_id" value="{{ $person_id ?? $personHasPendidikan->person_id }}" hidden>

<!-- Pendidikan Id Field -->
<div class="form-group">
    {!! Form::label('pendidikan_id', 'Pendidikan') !!}
    <div class="position-relative">
        {!! Form::select('pendidikan_id',$pendidikan,null, ['class' => 'form-control']) !!}
    </div>
</div>


<!-- Perguruan Tinggi Field -->
<div class="form-group">
    {!! Form::label('perguruan_tinggi', 'Perguruan Tinggi:') !!}
    <div class="position-relative">
        {!! Form::text('perguruan_tinggi', null, ['class' => 'form-control']) !!}
    </div>
</div>


<!-- Program Studi Field -->
<div class="form-group">
    {!! Form::label('program_studi', 'Program Studi:') !!}
    <div class="position-relative">
        {!! Form::text('program_studi', null, ['class' => 'form-control']) !!}
    </div>
</div>


<!-- Tahun Lulus Field -->
<div class="form-group">
    {!! Form::label('tahun_lulus', 'Tahun Lulus:') !!}
    <div class="position-relative">
        {!! Form::text('tahun_lulus', null, ['class' => 'form-control']) !!}
    </div>
</div>


{{--<!-- Person Has Pendidikancol Field -->--}}
{{--<div class="form-group">--}}
{{--    {!! Form::label('person_has_pendidikancol', 'Person Has Pendidikancol:') !!}--}}
{{--    <div class="position-relative">--}}
{{--        {!! Form::text('person_has_pendidikancol', null, ['class' => 'form-control']) !!}--}}
{{--    </div>--}}
{{--</div>--}}

<!-- Sudah di modifikasi -->
<!-- Submit Field -->
<div class="form-actions center">
    <a href="{!! url('people') !!}" class="btn btn-danger"> <i class="fa fa-close"></i> Batal</a>
    {!! Form::submit('Simpan', ['class' => 'btn btn-green mr-1']) !!}
</div>

resources/views/person_has_pendidikans/index.blade.php
@extends('layouts.app')
@section('content')
    <div class="content-body">
        <div class="row">
            <div class="col-12">
                @include('flash::message')
                <div class="clearfix"></div>
                <div class="card">
                    <div class="border-left-pink border-left-6 box-shadow-1 rounded">
                        <div class="card-content ">
                            <div class="card-body card-dashboard">
                                <div class="row">
                                    <div class="col-10 media-body mb-2">
                                        <div class="content-header-left breadcrumb-new">
                                            <span class="content-header-title mb-0 d-inline-block font-medium-4"><b>Person Has Pendidikans</b></span>
                                            <div class="breadcrumbs-top d-inline-block">
                                                <div class="breadcrumb-wrapper">
                                                    @include('layouts.breadcrumb')
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="col-2 text-right">
                                        <a href="{!! route('personHasPendidikans.create') !!}" class="btn btn-sm btn-green">Tambah Data</a>
                                    </div>
                                </div>
                                @include('person_has_pendidikans.table')
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/person_has_pendidikans/show.blade.php
@extends('layouts.app')
@section('content')
    <div class="content-body">
        <section id="horizontal-form-layouts">
            <div class="row">
                <div class="col-md-12">
                    <div class="card overflow-hidden">
                        <div class="card-content">
                            <div class="media align-items-stretch">
                                <div class="bg-blue p-2 media-middle">
                                    <i class="fa fa-align-left font-large-2 text-white"></i>
                                </div>
                                <div class="media-body p-1">
                                    <span class="blue font-medium-5"> Person Has Pendidikan</span><br>
                                    <span style="margin-top: -5px">Detail Person Has Pendidikan</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-12">
                    @include('adminlte-templates::common.errors')
                    <div class="card">
                        <div class="card-content collpase show">
                            <div class="card-body">
                                <form class="form form-horizontal">
                                    <div class="form-body">
                                        <h4 class="form-section">
                                            <a href="{!! route('personHasPendidikans.index') !!}" class="btn btn-icon danger btn-lg pl-0 ml-0"><i class="ft-arrow-left"></i> Kembali</a>
                                        </h4>
                                        @include('person_has_pendidikans.show_fields')
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
@endsection

resources/views/person_has_pendidikans/show_fields.blade.php
<!-- Sudah di modifikasi -->
<!-- Person Id Field -->
<div class="media">
    <div class="media-body">
        <h5 class="media-heading">
            {!! Form::label('person_id', 'Person Id:') !!}
        </h5>
        {!! $personHasPendidikan->person_id !!}
    </div>
</div>

<!-- Sudah di modifikasi -->
<!-- Pendidikan Id Field -->
<div class="media">
    <div class="media-body">
        <h5 class="media-heading">
            {!! Form::label('pendidikan_id', 'Pendidikan Id:') !!}
        </h5>
        {!! $personHasPendidikan->pendidikan_id !!}
    </div>
</div>

<!-- Sudah di modifikasi -->
<!-- Perguruan Tinggi Field -->
<div class="media">
    <div class="media-body">
        <h5 class="media-heading">
            {!! Form::label('perguruan_tinggi', 'Perguruan Tinggi:') !!}
        </h5>
        {!! $personHasPendidikan->perguruan_tinggi !!}
    </div>
</div>

<!-- Sudah di modifikasi -->
<!-- Program Studi Field -->
<div class="media">
    <div class="media-body">
        <h5 class="media-heading">
            {!! Form::label('program_studi', 'Program Studi:') !!}
        </h5>
        {!! $personHasPendidikan->program_studi !!}
    </div>
</div>

<!-- Sudah di modifikasi -->
<!-- Tahun Lulus Field -->
<div class="media">
    <div class="media-body">
        <h5 class="media-heading">
            {!! Form::label('tahun_lulus', 'Tahun Lulus:') !!}
        </h5>
        {!! $personHasPendidikan->tahun_lulus !!}
    </div>
</div>

<!-- Sudah di modifikasi -->
<!-- Person Has Pendidikancol Field -->
<div class="media">
    <div class="media-body">
        <h5 class="media-heading">
            {!! Form::label('person_has_pendidikancol', 'Person Has Pendidikancol:') !!}
        </h5>
        {!! $personHasPendidikan->person_has_pendidikancol !!}
    </div>
</div>

resources/views/person_has_pendidikans/table.blade.php
<!-- Sudah di modifikasi untuk Edit,Lihat,Hapus -->
<table class="table table-hover table-bordered table-striped default table-responsive">
    <colgroup>
        <col class="col-xs-1">
        <col class="col-xs-7">
    </colgroup>
    <thead>
    <tr>
        <th><code>#</code></th>
        <th>Person Id</th>
        <th>Pendidikan Id</th>
        <th>Perguruan Tinggi</th>
        <th>Program Studi</th>
        <th>Tahun Lulus</th>
        <th>Person Has Pendidikancol</th>
        <th style="text-align: center">Action</th>
    </tr>
    </thead>
    <tbody>
    @php
        $no = 1;
    @endphp
    @foreach($personHasPendidikans as $personHasPendidikan)
        <tr>
            <td>{!! $no++ !!}</td>
            <td>{!! $personHasPendidikan->person_id !!}</td>
            <td>{!! $personHasPendidikan->pendidikan_id !!}</td>
            <td>{!! $personHasPendidikan->perguruan_tinggi !!}</td>
            <td>{!! $personHasPendidikan->program_studi !!}</td>
            <td>{!! $personHasPendidikan->tahun_lulus !!}</td>
            <td>{!! $personHasPendidikan->person_has_pendidikancol !!}</td>
            <td>
                {!! Form::open(['route' => ['personHasPendidikans.destroy', $personHasPendidikan->id], 'method' => 'delete']) !!}
                <div class="btn-group" role="group" aria-label="Basic example">
                    <a href="{!! route('personHasPendidikans.show', [$personHasPendidikan->id]) !!}" class="btn btn-sm btn-success"><i class="fa fa-eye"></i></a>
                                       <a href="{!! route('personHasPendidikans.edit', [$personHasPendidikan->id]) !!}" class="btn btn-sm btn-warning"><i class="fa fa-pencil"></i></a>
                                       {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-sm btn-danger', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>